### ISSUE TITLE
Tab-completing code doesn't work in REPL plugin

### ISSUE THREAD

**Issue by binarytemple** [lfe-rebar3/repl#1]
is there any strategy for getting this working?

**Comment by oubiwann** [comment]
Quick reply now (if this doesn't help, I'll get you more details later):

Check out the `rebar.config` for the ltool project in the same Github org (lfe-rebar3). That project uses a bunch of the lfe rebar3 plugins, and thus supports commands for them like `rebar3 lfe repl`.

Let me know how it goes!

**Comment by oubiwann** [comment]
Ah, sorry -- I responded to an email from github, not in the ticket itself. I see the context of your question, now.

I need to ask Robert about a better way to start up the LFE shell programmatically, as there are a bunch of things not working (readline support, `^G`, errors on quitting, tab-completion, etc.). 

I'll keep this ticket open until we get the standard LFE tab-completion working.

**Comment by oubiwann** [comment]
There's a new rebar3 LFE plugin currently in development, and the new `rebar3 lfe repl` plugin just landed, and it's working great! (readline, arrows, history, history search, table completion, etc.) Check it out:
* https://github.com/lfe-rebar3/rebar3_lfe/blob/master/src/rebar3_lfe_prv_repl.erl

I'm going to close this ticket (and archive this project) ...
