### ISSUE TITLE
lfe repl task doesn't do anything with the passed options

### ISSUE THREAD

**Issue by oubiwann** [lfe-rebar3/repl#5]
The LFE REPL rebar3 plugin is derived from the rebar3 Erlang shell plugin. It is written to accept options, as noted in the help:

```
The LFE rebar3 LFE REPL plugin.

Start an LFE REPL for a project with its dependencies preloaded, similar to
'lfe -pa ebin -pa deps/*/ebin' with support for -name and -sname parameters.

Usage: rebar3 lfe repl [--name <name>] [--sname <sname>] [--apps <apps>]

  --name   Gives a long name to the node.
  --sname  Gives a short name to the node.
  --apps   A list of apps to boot before starting the shell. (E.g. --apps
           app1,app2,app3) Defaults to rebar.config {shell, [{apps,
           Apps}]} or relx apps if not specified.
```

However, passing values for these doesn't seem to chanve anything. This may actually be due to the way the LFE shell is written (you may not be able to set these options when starting `lfe_shell:server` as it is currently written -- will need to confer with @rvirding on that ... we've talked about this on the mail list and in other tickets, I just need to be sure).

**Comment by rvirding** [comment]
What is the actual command to start LFE all this results in? And what is the equivalent resulting Erlang command? Just so I know what is going on.

**Comment by oubiwann** [comment]
rebar3 does some interesting stuff to start up the Erlang shell, much of which I don't really understand. The command for starting the Erlang shell in rebar3 is simply this:

``` bash
$ rebar3 shell
```

However, it also allows for setting the name via `--name` and `--sname` or provide a custom config file via `--config` or start up apps (comma-separated) via `--apps`. For instance:

``` bash
$ rebar3 shell --sname foo --apps inets,crypto,ssl
```

The crazy shell start-up code I mentioned is here:
- https://github.com/rebar/rebar3/blob/master/src/rebar_prv_shell.erl

I basically converted all of that code to LFE for the rebar3 [repl plugin](https://github.com/lfe-rebar3/repl/tree/master/src). 

You can't use the plugins directly from their own repo, though -- you need a project that pulls in all the necessary plugins, so I created [ltool](https://github.com/lfe-rebar3/ltool) as a place to start experimenting with all the LFE plutins. You can run the LFE repl with the following commands:

``` bash
$ git clone git@github.com:lfe-rebar3/ltool.git
$ cd ltool
$ rebar3 lfe repl
```

As noted, however, passing the options has no impact since lfe_shell:server doesn't take `erl` options ...

**Comment by rvirding** [comment]
No, the lfe_shell:server shouldn't handle the `erl` options, the erlang shell doesn't do it either. Handling those options is normally done in the erlang startup before any shell is started. In the file you linked this is done explicitly before starting the shell. So the setup_name function on L225 handles name and sname and the maybe_boot_apps function on L208 boots any apps. The shell is started in setup_shell L113 but by calling user_drv:start it ensures that it is the erlang shell which is started. Here we would need to start the LFE shell instead. If you checkout lfe_init.erl on L46 you can see how I use user_drv:start to start an LFE shell, this should work here as well.

**Comment by rvirding** [comment]
I did some more checking in your code and I think one problem is that you explicitly start the shell and don't call user_drv:start. Try doing the same way I do in lfe_init.erl and see if that works. That should still not handle name, sname and apps but you do that explicitly as well. Have you tried print outs to see what happens? I love lfe_io:format :-)

**Comment by oubiwann** [comment]
I'm working on a new REPL plugin for rebar3, and have come back to trying to solve this.

In the plugin, I tried using `lfe_init:start/0` like you mentioned above, but I got this error:

```
=ERROR REPORT==== 13-Jul-2020::15:24:21.160817 ===
driver_select(0x00007f90aa7c02a0, 0, ERL_DRV_READ ERL_DRV_USE, 1) by fd (0/1) driver #Port<0.29> stealing control of fd=0 from input driver fd (0/1) #Port<0.3>
```

Looking at the code, I checked `rebar3`'s view of what the init args were, and it turns out there were some, so the proper code branch with the call to `user_drv:start` wasn't getting called. (Good to know that `lfe_init/start` isn't going to be generally usable in its current form.)

So, instead I called the function directly:
```erlang
user_drv:start(['tty_sl -c -e',{lfe_shell,start,[]}]).
```
It returns a PID successfully, with no error, but also no shell. Curious, I tried it in the Erlang shell, started with `rebar2 shell`, and got this result, also no shell, but the logger did pop up with an error:

```erlang
1> user_drv:start(['tty_sl -c -e',{lfe_shell,start,[]}]).
<0.208.0>
2> 2020-07-13T15:48:35.088276-05:00 error: Error in process <0.208.0> with exit value:, {badarg,[{erlang,register,[user,<0.209.0>],[]},{user,start_port,1,[{file,"user.erl"},{line,55}]}]}
2020-07-13T15:48:35.088321-05:00 error: driver_select(0x00007fae2a681e48, 0, ERL_DRV_READ ERL_DRV_USE, 1) by fd (0/1) driver #Port<0.12> stealing control of fd=0 from input driver tty_sl (tty_sl -c -e) #Port<0.9>
```

From the Erlang shell started by rebar3 I was able to get a working LFE REPL with the usual:

```
lfe_shell:start().
```

**Comment by oubiwann** [comment]
Ha! rebar3 offers support for passing in _exactly_ what you do with `lfe_init/start`, @rvirding! The rebar3 LFE REPL plugin code is so _tiny_ now! And, best of all, it works really well :-) 

Check out the tininess: 
* https://github.com/lfe-rebar3/rebar3_lfe/blob/master/src/rebar3_lfe_prv_repl.erl

**Comment by oubiwann** [comment]
I'm going to close this ticket now, since the new rebar3 plugin that uses the rebar3 shell under the hood correctly accepts the options passed to it :-)
