### ISSUE TITLE
Error starting repl

### ISSUE THREAD

**Issue by hdurer** [lfe-rebar3/repl#6]
I try a very simple:

```
    rebar3 new release foo
    cd foo
    edit rebar.config
    # just add one line:
    # {plugins, [{'lfe-repl', {git, "https://github.com/lfe-rebar3/repl.git", {tag, "0.1.1"}}}]}.
    rebar3 lfe shell
```

and that fails.
There is an error.  It starts with:

```
    ===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
    ===> Uncaught error: function_clause
    ===> Stack trace to the error location: [{proplists,get_value,
                                                     [applications,
                                                      {ok,
                                                       [{description,
                                                         "SASL  CXC 138 11"},
                                                        {id,[]},
                                                        {vsn,"2.6.1"},
                                                        {modules,
                                                         [sasl,alarm_handler,
                                                          format_lib_supp,
                                                          misc_supp,overload,rb,
                                                          rb_format_supp,
                                                          release_handler,
                                                          release_handler_1,
                                                          erlsrv,sasl_report,
                                                          sasl_report_tty_h,
                                                          sasl_report_file_h,si,
                                                          si_sasl_supp,systools,
                                                          systools_make,
                                                          systools_rc,
                                                          systools_relup,
                                                          systools_lib]},
                                                        {maxP,infinity},
                                                        {maxT,infinity},

```

**Comment by hdurer** [comment]
```
Rebar3 report
 version 3.0.0-beta.3+build.3089.ref97ae8d6
 generated at 2016-02-09T21:00:51+00:00
=================
Please submit this along with your issue at https://github.com/rebar/rebar3/issues (and feel free to edit out private information, if any)
-----------------
Task: lfe
Entered as:
  lfe repl
-----------------
Operating System: x86_64-unknown-linux-gnu
ERTS: Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:4:4] [async-threads:0] [kernel-poll:false]
Root Directory: /usr/lib/erlang
Library directory: /usr/lib/erlang/lib
-----------------
Loaded Applications:
bbmustache: 1.0.4
certifi: 0.1.1
common_test: 1.11.1
compiler: 6.0.2
crypto: 3.6.2
dialyzer: 2.8.2
edoc: 0.7.17
erlware_commons: 0.16.0
eunit: 2.2.12
getopt: 0.8.2
inets: 6.1
kernel: 4.1.1
providers: 1.5.0
public_key: 1.1
relx: 3.7.1
sasl: 2.6.1
snmp: 5.2.1
ssl_verify_hostname: 1.0.5
stdlib: 2.7
syntax_tools: 1.7
tools: 2.8.2

-----------------
Escript path: /usr/local/bin/rebar3
Providers:
  app_discovery as clean compile compile compile compile compile cover ct deps dialyzer do edoc escriptize eunit help install install_deps list lock new path pkgs release relup repl report shell tar tree unlock update upgrade upgrade upgrade version xref 
```

**Comment by hdurer** [comment]
Looking at the code, that might/should be fixed by arpunk's code: https://github.com/arpunk/repl/commit/ab1c4d4a97bb1b446778560356b1d7923209a19f

**Comment by hdurer** [comment]
After that fix I also need to change `update-env`...  Nothing seems to get the expected form of parameters.

**Comment by oubiwann** [comment]
Thanks for the heads-up about @arpunk's patch -- I've just merged that.

**Comment by oubiwann** [comment]
In order to use the rebar3 LFE plugins, you need to do several things in your `rebar.config` file. (I'm not sure where your problem is, exactly, so I'm going to start at the bottom -- apologies if you're already done all that!)

Here's the minimum for running the LFE REPL in a project:

``` erlang
{deps, [
   {lfe, ".*", {git, "https://github.com/rvirding/lfe.git", {tag, "v0.10.1"}}}
  ]}.

{plugins, [
   {'lfe-compile', ".*", 
     {git, "https://github.com/lfe-rebar3/compile.git", {tag, "0.2.1"}}},
   {'lfe-repl', ".*", 
     {git, "https://github.com/lfe-rebar3/repl.git", {tag, "0.1.2"}}}
  ]}.

{provider_hooks, [
   {pre, [{compile, {lfe, compile}}]}
  ]}.
```

That should get you to the point where `rebar3 lfe repl` works. After that, you'll see another series of issues (lack of `readline` support, etc.). There are issues open for those.

If you're still having problems after that's set up, let me know, and I'll see if I can duplicate the issue(s).

**Comment by arpunk** [comment]
@hdurer Hi there, you are right. I tried to get a fix for it but I ended up with another error and my time ran out. Good thing you got ahead! I remember I stopped because I wanted to understand the shell plugin for rebar3 in order to see what changed/can be updated.

@oubiwann I'm so sorry, I didn't submit the PR because my fix trigger another bug and I stopped to try to understand rebar3 shell more in-depth.

Btw this is the only thing left in order to have proper Erlang/LFE releases with rebar3/relx IIRC.

**Comment by arpunk** [comment]
@hdurer As a workaround, you can start the normal `rebar3 shell` and then load up a REPL with `lfe_shell:server().`. This makes rebar3 to load and start up all the apps needed in order to work.

**Comment by hdurer** [comment]
Thanks folks.

My diff to get things working is 

```
diff --git a/src/lr3-repl-cfg.lfe b/src/lr3-repl-cfg.lfe
index 45b5304..b15d2f7 100644
--- a/src/lr3-repl-cfg.lfe
+++ b/src/lr3-repl-cfg.lfe
@@ -12,7 +12,9 @@

 (defun update-env
   ((`#(,app #(,key ,val)))
-    (application:set_env app key val)))
+   (application:set_env app key val))
+  ((`#(,_app ()))
+   'ok))
```

No idea if that is the correct behaviour of course.  ☺

Oh, I see that besides unpacking that ok-tuple I also messed with `load-apps-normalized`.  That's a rather obscure function anyway and is missing (for me) another case.
I replaced it with this.  As you can tell, I have no idea what I am doing:

```
(defun load-apps-normalized (apps)
  (lists:map #'load-app-normalized/1 apps))

(defun load-app-normalized
  ((`#(,app ,_))
   app)
  ((`#(,app ,_version load))
   app)
  ((app) (when (is_atom app))
   app)
  ((`#(app_info_t ,app ,_src ,_undef ,_app ,_version ,_root ,_attributes ,_modules ,_modules2 ,_what ,_dict1 ,_dict2 ,_int ,_somethingelse ,_yetmore ,_undef2 ,_undef3 ,_b1 ,_b2 ,_b3))
   `#(ok ,app))
  ((x)
   (rebar_api:error "Got unexpected arg in load-app-normalized: ~p" `(,x))
   x))
```

**Comment by hdurer** [comment]
BTW: To get just an LFE repl, why would I need all that?  Wouldn't the lfe-repl plugin be enough? 

lfe-compile and the provider hook would be needed if I had some lfe source code I guess.

And I am still trying to understand why I need the dep on lfe itself -- for the lfe runtime, I assume?  But I'd hope the the lfe-repl plugin would bring in its own lfe dependency, or not?  (It would be wrong if you need to add deps for plugin that you only want for the development process.)

**Comment by oubiwann** [comment]
@hdurer Yeah, sorry -- I was making assumptions about how you wanted to use this.

rebar3 is structured so that plugin deps and project deps are completely separate. You could theoretically have an LFE plugin for the REPL with no project dependency upon LFE.

I haven't attempted to test minimal `rebar.config` files; I don't know what happens if you're not interested in running `rebar3 lfe compile` but want to be able to run `rebar3 lfe repl` ...

**Comment by oubiwann** [comment]
There's a new rebar3 LFE plugin currently in development, and the new `rebar3 lfe repl` plugin just landed, and it's working great! (readline, arrows, history, history search, table completion, etc.) Check it out:
* https://github.com/lfe-rebar3/rebar3_lfe/blob/master/src/rebar3_lfe_prv_repl.erl

I'm going to close this ticket (and archive this project) ...
