### ISSUE TITLE
Erratic behaviour in the rebar3 repl

### ISSUE THREAD

**Issue by sashaafm** [lfe-rebar3/repl#9]
I've installed the lfe-repl plugin for rebar3 alongside lfe-compile. However, the lfe-repl plugin offers a REPL with a different behaviour from the standard LFE REPL. For example, I can't fetch the history since the keyboard's up and down arrow are not decoded properly and I can't also move around with the cursor with the left and right arrow keys for the same reason.

I'm on MacOS Sierra.

**Comment by oubiwann** [comment]
There's a new rebar3 LFE plugin currently in development, and the new `rebar3 lfe repl` plugin just landed, and it's working great! (readline, arrows, history, history search, table completion, etc.) Check it out:
* https://github.com/lfe-rebar3/rebar3_lfe/blob/master/src/rebar3_lfe_prv_repl.erl

I'm going to close this ticket (and archive this project) ...
